export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0f0f0f" },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0f0f0f",
    padding: 32,
  },

  header: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 14,
    backgroundColor: "#000",
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a1a",
  },
  headerTitle: { color: "#E0AA3E", fontSize: 20, fontWeight: "bold" },
  headerSub: { color: "#666", fontSize: 12, marginTop: 2 },

  tabs: {
    flexDirection: "row",
    backgroundColor: "#000",
    paddingHorizontal: 12,
    paddingBottom: 10,
    gap: 8,
  },
  tab: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  tabActive: { backgroundColor: "#E0AA3E", borderColor: "#E0AA3E" },
  tabText: { color: "#888", fontSize: 12, fontWeight: "600" },
  tabTextActive: { color: "#111" },
  lockIcon: { fontSize: 48, marginBottom: 16 },
  notAuthTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  notAuthText: {
    color: "#888",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },

  section: { padding: 16 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  sectionCount: { color: "#666", fontSize: 13 },

  card: {
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#E0AA3E",
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: { color: "#fff", fontSize: 15, fontWeight: "600", flex: 1 },
  cardSub: { color: "#888", fontSize: 12, marginTop: 3 },
  cardBadge: {
    backgroundColor: "rgba(224,170,62,0.15)",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginLeft: 8,
  },
  cardBadgeText: { color: "#E0AA3E", fontSize: 11, fontWeight: "bold" },

  btnRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  btnEdit: {
    flex: 1,
    backgroundColor: "#1e3a5f",
    borderRadius: 6,
    paddingVertical: 7,
    alignItems: "center",
  },
  btnEditText: { color: "#4a9eff", fontSize: 12, fontWeight: "600" },
  btnDelete: {
    flex: 1,
    backgroundColor: "#3a1a1a",
    borderRadius: 6,
    paddingVertical: 7,
    alignItems: "center",
  },
  btnDeleteText: { color: "#ff6b6b", fontSize: 12, fontWeight: "600" },
  btnAdd: {
    backgroundColor: "#1a3a1a",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#2a5a2a",
  },
  btnAddText: { color: "#4caf50", fontSize: 13, fontWeight: "bold" },

  userCard: {
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#4a90d9",
  },
  userName: { color: "#fff", fontSize: 15, fontWeight: "600" },
  userEmail: { color: "#888", fontSize: 12, marginTop: 2 },
  userRole: { color: "#E0AA3E", fontSize: 11, marginTop: 4 },
});
