import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0f0f0f" },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0f0f0f",
    padding: 32,
  },

  header: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 14,
    backgroundColor: "#000",
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a1a",
  },
  headerTitle: { color: "#E0AA3E", fontSize: 20, fontWeight: "bold" },
  headerSub: { color: "#666", fontSize: 12, marginTop: 2 },

  tabs: {
    flexDirection: "row",
    backgroundColor: "#000",
    paddingHorizontal: 12,
    paddingBottom: 10,
    gap: 8,
  },
  tab: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  tabActive: { backgroundColor: "#E0AA3E", borderColor: "#E0AA3E" },
  tabText: { color: "#888", fontSize: 12, fontWeight: "600" },
  tabTextActive: { color: "#111" },

  lockIcon: { fontSize: 48, marginBottom: 16 },
  notAuthTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  notAuthText: {
    color: "#888",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },

  section: { padding: 16 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  sectionCount: { color: "#666", fontSize: 13 },

  card: {
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#E0AA3E",
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: { color: "#fff", fontSize: 15, fontWeight: "600", flex: 1 },
  cardSub: { color: "#888", fontSize: 12, marginTop: 3 },
  cardBadge: {
    backgroundColor: "rgba(224,170,62,0.15)",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginLeft: 8,
  },
  cardBadgeText: { color: "#E0AA3E", fontSize: 11, fontWeight: "bold" },

  btnRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  btnEdit: {
    flex: 1,
    backgroundColor: "#1e3a5f",
    borderRadius: 6,
    paddingVertical: 7,
    alignItems: "center",
  },
  btnEditText: { color: "#4a9eff", fontSize: 12, fontWeight: "600" },
  btnDelete: {
    flex: 1,
    backgroundColor: "#3a1a1a",
    borderRadius: 6,
    paddingVertical: 7,
    alignItems: "center",
  },
  btnDeleteText: { color: "#ff6b6b", fontSize: 12, fontWeight: "600" },
  btnAdd: {
    backgroundColor: "#1a3a1a",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#2a5a2a",
  },
  btnAddText: { color: "#4caf50", fontSize: 13, fontWeight: "bold" },

  userCard: {
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#4a90d9",
  },
  userName: { color: "#fff", fontSize: 15, fontWeight: "600" },
  userEmail: { color: "#888", fontSize: 12, marginTop: 2 },
  userRole: { color: "#E0AA3E", fontSize: 11, marginTop: 4 },

  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 14,
    borderTopWidth: 3,
  },
  statLabel: {
    color: "#888",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  statValue: { color: "#fff", fontSize: 22, fontWeight: "bold" },
  statSub: { color: "#555", fontSize: 11, marginTop: 4 },

  topRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#1a1a1a",
    borderRadius: 8,
    marginBottom: 8,
    gap: 10,
  },
  topRank: { fontSize: 18, fontWeight: "bold", width: 30 },
  topTitle: { color: "#fff", fontSize: 14, flex: 1 },
  topCount: { color: "#E0AA3E", fontSize: 13, fontWeight: "bold" },

  occRow: {
    backgroundColor: "#1a1a1a",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  occFilm: { color: "#fff", fontSize: 13, fontWeight: "600", marginBottom: 2 },
  occTime: { color: "#666", fontSize: 11, marginBottom: 8 },
  occBarTrack: {
    height: 6,
    backgroundColor: "#2a2a2a",
    borderRadius: 3,
    marginBottom: 4,
  },
  occBarFill: { height: 6, borderRadius: 3 },
  occBottom: { flexDirection: "row", justifyContent: "space-between" },
  occPct: { fontSize: 12, fontWeight: "bold" },
  occTickets: { color: "#888", fontSize: 11 },

  occTabs: { flexDirection: "row", gap: 8, marginBottom: 12 },
  occTab: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  occTabActive: { backgroundColor: "#E0AA3E", borderColor: "#E0AA3E" },
  occTabText: { color: "#888", fontSize: 12 },
  occTabTextActive: { color: "#111", fontWeight: "bold" },

  empty: { alignItems: "center", padding: 32 },
  emptyIcon: { fontSize: 36, marginBottom: 12 },
  emptyText: { color: "#555", fontSize: 14 },

  loadingText: { color: "#888", marginTop: 12 },
  errorText: { color: "#ff6b6b", textAlign: "center", padding: 16 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "flex-end",
  },
  modalBox: {
    backgroundColor: "#1a1a1a",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "85%",
  },
  modalTitle: {
    color: "#E0AA3E",
    fontSize: 17,
    fontWeight: "bold",
    marginBottom: 16,
  },
  modalLabel: { color: "#888", fontSize: 12, marginBottom: 4 },
  modalInput: {
    backgroundColor: "#0f0f0f",
    borderWidth: 1,
    borderColor: "#2a2a2a",
    borderRadius: 8,
    color: "#fff",
    padding: 10,
    fontSize: 14,
  },
  modalBtns: { flexDirection: "row", gap: 10, marginTop: 16 },
  modalBtnCancel: {
    flex: 1,
    backgroundColor: "#2a2a2a",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  modalBtnCancelText: { color: "#888", fontWeight: "600" },
  modalBtnSave: {
    flex: 1,
    backgroundColor: "#E0AA3E",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  modalBtnSaveText: { color: "#111", fontWeight: "bold" },

  helperBox: {
    backgroundColor: "#111",
    borderRadius: 8,
    padding: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  helperTitle: {
    color: "#E0AA3E",
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 6,
  },
  helperSub: {
    color: "#888",
    fontSize: 11,
    marginBottom: 4,
    fontWeight: "600",
  },
  helperRow: { color: "#aaa", fontSize: 11, marginBottom: 2 },
});
