import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0a0a0a" },

  header: {
    alignItems: "center",
    padding: 24,
    backgroundColor: "#141414",
    borderBottomWidth: 1,
    borderBottomColor: "#2a2a2a",
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#2a2a2a",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  avatarText: { fontSize: 36 },
  profileTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 16,
  },
  statsRow: { flexDirection: "row", gap: 24, marginBottom: 20 },
  statBox: { alignItems: "center" },
  statNumber: { fontSize: 28, fontWeight: "800", color: "#E50914" },
  statLabel: { fontSize: 12, color: "#888", marginTop: 2 },
  logoutBtn: {
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E50914",
  },
  logoutBtnText: { color: "#E50914", fontWeight: "600", fontSize: 14 },

  section: { padding: 16 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 16,
  },

  tabsRow: { flexDirection: "row", marginBottom: 16 },
  tab: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#1e1e1e",
    marginRight: 8,
    gap: 6,
  },
  tabActive: { backgroundColor: "#E50914" },
  tabText: { color: "#888", fontSize: 13, fontWeight: "500" },
  tabTextActive: { color: "#fff", fontWeight: "700" },
  tabCount: {
    backgroundColor: "#2a2a2a",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  tabCountActive: { backgroundColor: "rgba(255,255,255,0.25)" },
  tabCountText: { color: "#fff", fontSize: 11, fontWeight: "700" },

  card: {
    backgroundColor: "#1a1a1a",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#2a2a2a",
    overflow: "hidden",
  },
  cardUsed: { opacity: 0.65 },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  cinemaName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#888",
    letterSpacing: 1,
  },

  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  badge_valid: { backgroundColor: "#0d6e2e" },
  badge_expired: { backgroundColor: "#555" },
  badge_used: { backgroundColor: "#7a1a1a" },
  badge_cancelled: { backgroundColor: "#444" },
  badgeText: { color: "#fff", fontSize: 11, fontWeight: "700" },

  stamp: {
    position: "absolute",
    top: 20,
    right: -20,
    backgroundColor: "#7a1a1a",
    paddingHorizontal: 24,
    paddingVertical: 4,
    transform: [{ rotate: "15deg" }],
    zIndex: 1,
  },
  stampText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
  },

  movieTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 12,
  },

  metaRow: { flexDirection: "row", gap: 24, marginBottom: 12 },
  metaLabel: {
    fontSize: 11,
    color: "#666",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  metaValue: { fontSize: 13, color: "#ccc", fontWeight: "500" },

  seatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 12,
  },
  seatBadge: {
    backgroundColor: "#252525",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#333",
  },
  seatBadgeText: { color: "#ccc", fontSize: 12, fontWeight: "600" },

  actions: { flexDirection: "row", gap: 8, marginTop: 4 },
  cancelBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#2a0a0a",
    borderWidth: 1,
    borderColor: "#E50914",
    alignItems: "center",
  },
  cancelBtnText: { color: "#E50914", fontSize: 13, fontWeight: "600" },
  qrBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#1e1e1e",
    borderWidth: 1,
    borderColor: "#333",
    alignItems: "center",
  },
  qrBtnText: { color: "#aaa", fontSize: 13, fontWeight: "600" },

  qrSection: {
    alignItems: "center",
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#2a2a2a",
  },
  qrImage: { width: 180, height: 180, borderRadius: 8, marginBottom: 10 },
  ticketCode: { color: "#555", fontSize: 10, fontFamily: "monospace" },

  empty: { alignItems: "center", paddingVertical: 48, gap: 12 },
  emptyIcon: { fontSize: 48 },
  emptyText: { color: "#666", fontSize: 15 },
  errorText: {
    color: "#E50914",
    fontSize: 14,
    textAlign: "center",
    marginTop: 40,
  },
});
