import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const SEAT_SIZE = Math.floor((width - 80) / 10);

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#141414" },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#141414",
  },
  loadingText: { color: "#fff", marginTop: 10 },
  errorText: {
    color: "#ff6b6b",
    fontSize: 15,
    textAlign: "center",
    padding: 20,
  },

  // Header
  header: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 14,
    backgroundColor: "#000",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backBtn: { padding: 4 },
  backText: { color: "#fff", fontSize: 15 },
  headerTitle: { color: "#fff", fontSize: 18, fontWeight: "bold", flex: 1 },

  // Hall info
  hallInfo: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#1a1a1a",
    borderBottomWidth: 1,
    borderBottomColor: "#222",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  hallName: {
    color: "#E0AA3E",
    fontSize: 13,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  hallCapacity: { color: "#888", fontSize: 12 },

  // Screen
  screenWrapper: { alignItems: "center", marginTop: 20, marginBottom: 28 },
  screen: {
    width: width * 0.7,
    height: 36,
    backgroundColor: "#2a2010",
    borderTopWidth: 3,
    borderTopColor: "#E0AA3E",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  screenText: {
    color: "#E0AA3E",
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 6,
  },

  // Seat grid
  seatGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 24,
  },
  seat: {
    width: SEAT_SIZE,
    height: SEAT_SIZE,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  seatAvailable: { backgroundColor: "#2a2a2a" },
  seatSelected: { backgroundColor: "#E0AA3E" },
  seatReserved: { backgroundColor: "#1a1a1a", opacity: 0.4 },
  seatVip: { borderWidth: 1, borderColor: "#E0AA3E" },
  seatVipAvailable: { backgroundColor: "rgba(224,170,62,0.1)" },
  seatText: { fontSize: 8, fontWeight: "bold" },
  seatTextAvailable: { color: "#888" },
  seatTextSelected: { color: "#121212" },
  seatTextReserved: { color: "transparent" },

  // Legend
  legend: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 16,
    marginHorizontal: 16,
    marginBottom: 20,
    padding: 12,
    backgroundColor: "#1a1a1a",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendBox: {
    width: 18,
    height: 16,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  legendText: {
    color: "#aaa",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Footer
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#2a2a2a",
    backgroundColor: "#0f0f0f",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerInfo: {},
  footerLabel: { color: "#888", fontSize: 12 },
  footerCount: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  footerPrice: { color: "#E0AA3E", fontSize: 13 },
  bookBtn: {
    backgroundColor: "#E0AA3E",
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 8,
  },
  bookBtnDisabled: { backgroundColor: "#2a2a2a" },
  bookBtnText: { color: "#121212", fontWeight: "bold", fontSize: 15 },
  bookBtnTextDisabled: { color: "#555" },

  //Payment modal
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#141414",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "rgba(224,170,62,0.35)",
    maxHeight: "90%",
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#333",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  modalClose: {
    position: "absolute",
    top: 16,
    right: 16,
    padding: 8,
    zIndex: 10,
  },
  modalCloseText: { color: "#666", fontSize: 18 },
  modalScroll: { padding: 24 },

  modalTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 4,
  },
  modalSubtitle: {
    color: "#666",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 20,
  },

  // Summary
  summary: {
    backgroundColor: "#0f0f0f",
    borderWidth: 1,
    borderColor: "#2a2a2a",
    borderRadius: 10,
    padding: 14,
    marginBottom: 20,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#1e1e1e",
  },
  summaryRowLast: { borderBottomWidth: 0 },
  summaryLabel: { color: "#ccc", fontSize: 14 },
  summaryLabelVip: { color: "#E0AA3E" },
  vipBadge: {
    backgroundColor: "rgba(224,170,62,0.15)",
    borderWidth: 1,
    borderColor: "rgba(224,170,62,0.5)",
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
    marginRight: 6,
  },
  vipBadgeText: { color: "#E0AA3E", fontSize: 9, fontWeight: "bold" },
  summaryPrice: { color: "#E0AA3E", fontWeight: "600", fontSize: 14 },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(224,170,62,0.3)",
    marginTop: 6,
  },
  totalLabel: { color: "#fff", fontWeight: "bold", fontSize: 15 },
  totalAmount: { color: "#E0AA3E", fontWeight: "bold", fontSize: 20 },

  // Payment methods
  methods: { flexDirection: "row", gap: 8, marginBottom: 20 },
  methodBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    borderColor: "#2a2a2a",
    borderRadius: 10,
    gap: 4,
  },
  methodBtnActive: {
    borderColor: "#E0AA3E",
    backgroundColor: "rgba(224,170,62,0.08)",
  },
  methodIcon: { fontSize: 20 },
  methodLabel: { color: "#888", fontSize: 11 },
  methodLabelActive: { color: "#E0AA3E" },

  // Card form
  cardPreview: {
    backgroundColor: "#1e1a0e",
    borderWidth: 1,
    borderColor: "rgba(224,170,62,0.4)",
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
  },
  cardChip: {
    color: "rgba(224,170,62,0.6)",
    fontSize: 14,
    letterSpacing: 2,
    marginBottom: 12,
  },
  cardNumber: {
    color: "#E0AA3E",
    fontSize: 16,
    letterSpacing: 3,
    fontFamily: "monospace",
    marginBottom: 12,
  },
  cardBottom: { flexDirection: "row", justifyContent: "space-between" },
  cardBottomText: {
    color: "rgba(224,170,62,0.7)",
    fontSize: 11,
    letterSpacing: 1,
  },

  field: { marginBottom: 14 },
  fieldLabel: {
    color: "#888",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  fieldInput: {
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    borderColor: "#2f2f2f",
    borderRadius: 8,
    color: "#fff",
    padding: 12,
    fontSize: 15,
  },
  fieldRow: { flexDirection: "row", gap: 12 },
  fieldHalf: { flex: 1 },

  // PayPal
  paypalBox: {
    backgroundColor: "#0f0f0f",
    borderWidth: 1,
    borderColor: "#2a2a2a",
    borderRadius: 10,
    padding: 24,
    alignItems: "center",
    marginBottom: 20,
    gap: 12,
  },
  paypalLogo: { flexDirection: "row" },
  paypalP1: {
    color: "#4a90d9",
    fontSize: 28,
    fontWeight: "900",
    fontStyle: "italic",
  },
  paypalP2: {
    color: "#009cde",
    fontSize: 28,
    fontWeight: "900",
    fontStyle: "italic",
  },
  paypalText: {
    color: "#888",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
  },
  paypalSecure: {
    color: "#4a7c4a",
    fontSize: 12,
    backgroundColor: "rgba(74,124,74,0.1)",
    borderWidth: 1,
    borderColor: "rgba(74,124,74,0.3)",
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
  },

  // Szép kártya
  szepHeader: {
    backgroundColor: "#0a1628",
    borderWidth: 1,
    borderColor: "rgba(0,120,200,0.35)",
    borderRadius: 10,
    padding: 16,
    alignItems: "center",
    marginBottom: 16,
  },
  szepLogo: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 1,
  },
  szepLogoAccent: { color: "#00a0e9" },
  szepSub: { color: "#6aacdc", fontSize: 12, marginTop: 4 },

  // Pay button
  payBtn: {
    backgroundColor: "#E0AA3E",
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
    marginBottom: 16,
  },
  payBtnDisabled: { backgroundColor: "#2a2a2a" },
  payBtnProcessing: { backgroundColor: "rgba(224,170,62,0.3)" },
  payBtnText: { color: "#111", fontWeight: "bold", fontSize: 16 },
  payBtnTextDisabled: { color: "#555" },
  secureNote: {
    color: "#444",
    fontSize: 12,
    textAlign: "center",
    marginBottom: 8,
  },

  // Success screen
  successOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.92)",
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(76,175,80,0.15)",
    borderWidth: 2,
    borderColor: "#4caf50",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  successIconText: { fontSize: 36, color: "#4caf50" },
  successTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
  },
  successText: {
    color: "#888",
    fontSize: 15,
    textAlign: "center",
    lineHeight: 22,
  },
});
